### ISSUE TITLE
How should we handle configuration of backups?

### ISSUE THREAD

**Issue by weaverba137** [desihub/desiBackup#1]
While preparing this code to back up the `oak1` reduction, I was thinking about how to handle the configuration of the backups.  The low-level backup system, in the [hpsspy](https://github.com/weaverba137/hpsspy) package, needs a JSON file which specifies how files on disk map to files on HPSS.  desiBackup has the necessary file in `etc/desi.json`, and the shell script `desiBackup.sh` passes this file to the low-level backup system.

The question is, do we:

* update this file in GitHub every time there is something new to back up, and cut a new tag?
* update this file in GitHub, but don't bother tagging, *i.e.* install a git clone instead of a tagged version?
* tag a stable version, but create copies of `etc/desi.json` as needed to backup stuff?
* do something else?

PS, while dusting off & testing desiBackup, I've already made a backup of `oak1`, but this could be deleted at will for further testing.

**Comment by weaverba137** [comment]
PS, I added some details about configuration and use to the README.rst file.

**Comment by sbailey** [comment]
Quick question about intended usage: is desiBackup primarily for backing up static directories where we have finished updating them and want to make a snapshot (e.g. a major pipeline reprocessing), or is it intended to also backup work-in-progress, like daily reductions?

**Comment by weaverba137** [comment]
Primarily for static directories.  The underlying library, hpsspy, was originally designed to backup entire SDSS data releases (by definition static).  For things like daily reductions, it is much simpler to just issue a "bare" htar command to back up that day's directories.

**Comment by weaverba137** [comment]
Based on discussions with @sbailey, we decided that installing a git clone would be the best way to proceed.
