### ISSUE TITLE
New data in datachallenge directory

### ISSUE THREAD

**Issue by weaverba137** [desihub/desiBackup#12]
Examine files in the datachallenge directory that are newer than existing backups.  In some cases there is just one file that changed.

- [x] `surveysim2018/weather/README`; owner `sjbailey`
- [x] `dc17a-twopct/spectro/redux/dc17a2/dc17a2_qa.json`; owner `sjbailey`
- [x] `dc17a-twopct/spectro/redux/dc17a2/exposures/NIGHT/EXPID/qa-SPECTROGRAPH-EXPID.yaml`; owner `sjbailey`
- [x] `dc17a-twopct/spectro/redux/dc17a2/exposures/NIGHT/EXPID/qa-(sky|flux)-SPECTROGRAPH-EXPID.png`; owner `sjbailey`
- [x] `dc17a-twopct/spectro/redux/dc17a2/calib2d/NIGHT/qa-z5-EXPID.yaml`; owner `sjbailey`
- [x] `reference_runs/18.2/survey/test-tiles.fits`; owner `mmagana`

This is a nice one because once these issues are resolved, we should be able to go directly from red to green/Complete.

Assigning to @sbailey since he is the owner of most of these files.

**Comment by sbailey** [comment]
> surveysim2018/weather/README; owner sjbailey

Ideally this would be included in the backup, though I recognize that the system is intended for backing up frozen archival data and not incrementally adding pieces.  For cases like this, how big a hassle is it to just discard the previous backup and replace it with a new one that includes the extra file?

> dc17a-twopct qa files

These are redundant with the files in the separate `dc17a-twopct/spectro/redux/dc17a2/QA/` directory, and were left over from running QA with the wrong output directory options.  I removed them.

> reference_runs/18.2/survey/test-tiles.fits

@weaverba137 asked Marianna if she still wants/needs this.

**Comment by weaverba137** [comment]
It's easy to redo the backup of surveysim2018.  I just needed confirmation of what you wanted to do.

**Comment by weaverba137** [comment]
Backup of surveysim2018 has been redone.

**Comment by weaverba137** [comment]
Moved the one remaining file out of the way; `datachallenge/` is now green.
