### ISSUE TITLE
New data in spectro directory

### ISSUE THREAD

**Issue by weaverba137** [desihub/desiBackup#14]
Examine files in the spectro directory that are newer than existing backups.

- [x] `spectro/redux/sjb/dogwood` has new data, but even the new data are from 2015!  Maybe just re-backup.
- [x] Are other directories in `spectro/redux/sjb` archival?
- [x] `redux/oak1/bricks/3127p090/blat.h5`: Just one file.  Not sure who originally owned it.

**Comment by sbailey** [comment]
No need to re-backup `spectro/redux/sjb/dogwood`, or anything else in `spectro/redux/sjb` (which I don't even see anymore, so perhaps I already cleaned that up.  I removed blat.h5 which was mine.  i.e. I think this ticket can be closed unless there is any action needed to cleanup desiBackup config to ignore these.

**Comment by weaverba137** [comment]
I will close after I refresh the backup status.
