### ISSUE TITLE
Configure cmx/ directory for backups after end of CI run

### ISSUE THREAD

**Issue by weaverba137** [desihub/desiBackup#16]
@sbailey, is the desi/cmx/ci data set now static and ready for backup?

**Comment by sbailey** [comment]
The desi/cmx/ci/tiles/ directory is static and ready for backup.  Thanks.

There is some possibility that other CI analyses will appear in desi/cmx/ci/ at a level parallel to tiles/, so please configure and backup tiles/ separately in a way that anticipates the possibility of other things showing up parallel to that for future backup.

**Comment by weaverba137** [comment]
Sure, that's no problem.
