### ISSUE TITLE
backup daily/tiles/archive directories

### ISSUE THREAD

**Issue by sbailey** [desihub/desiBackup#26]
Please add tape backup configurations for $DESI_ROOT/spectro/redux/daily/tiles/archive/TILEID/ARCHIVEDATE .  These are the basis of the MTL ledger update decisions and should be archived as part of the history of operations.

Unlike the rest of the daily prod, the tiles/archive/TILEID/ARCHIVEDATE directories are guaranteed to be frozen once written and thus are safe to backup.  New TILEID/ARCHIVEDATE directories may appear (including for the same TILEID that had previously been archived under and earlier ARCHIVEDATE), but the contents of the existing ones won't change once written.

These are ~5 GB each, which is a bit on the small side for htar files.  If we need to go to a larger bundling, all tiles on a given ARCHIVEDATE could be put together, though that's a little "unnatural" given the TILEID/ARCHIVEDATE organization instead of ARCHIVEDATE/TILEID, but I don't think that's a blocking factor if we need to go for bigger bundles.

**Comment by weaverba137** [comment]
See also desihub/desispec#1762.
