### ISSUE TITLE
add more desi.json documentation

### ISSUE THREAD

**Issue by sbailey** [desihub/desiBackup#3]
Motivated by #2, add more documentation about how to add a new entry to `etc/desi.json`, e.g.

1. naming constraints on the tar files, and whether those are best-practices guidelines or actually required for desiBackup and restore to work properly.
2. worked examples for using regex groups to map N>>1 directories into N>>1 tar files, and how much one should worry about the resulting size of the tar file (and how to tell).
3. worked examples for how to map the files in a directory into a tarball without accidentally mapping files in subdirectories.

Since json files don't allow comments, the existing `etc/desi.json` is only partially useful for deriving these patterns.

**Comment by weaverba137** [comment]
For my own notes, this documentation is sufficiently important that it should be added to the hpsspy package, and it will be visible at http://hpsspy.readthedocs.io
