### ISSUE TITLE
add etc/desi.json validation tools

### ISSUE THREAD

**Issue by sbailey** [desihub/desiBackup#4]
Add tools for validating the backup specifications in `etc/desi.json`, in particular:

1. do any regexes not match any files?
2. are any files in the directory tree not covered by a regex and not in the exclude list?
3. are any files covered by more than one regex?
4. would any tar specification result in a tarball > 1TB?
5. a `--manifest` option (or some equivalent name) that would generate a manifest of what files would go into what tarballs.  e.g. perhaps this would point to a directory and it would create fake *.tar files in the same hierarchy and naming that would end up on HPSS, but the contents of those files would be the listing of file paths rather than the contents of the files themselves (like `tar -tf blat.tar` would report).  This would allow someone to do a dry run and check if the results are intended before actually trying to send TB of data to HPSS.

Note that this validation would need to be run at NERSC since it needs access to the actual files; this isn't just the json syntax check of the travis test.

**Comment by weaverba137** [comment]
For my own notes, I think item 5 already exists, in the form of an intermediate data file used to actually create the hsi/htar commands.
